# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rankin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankin_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Chofer')),
                ('rankin_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Usuario')),
            ],
            options={
                'verbose_name': 'Rankin',
                'verbose_name_plural': 'Rankins',
            },
        ),
    ]
